@startuml

title __JPA's Class Diagram__\n

  namespace com.example.demo {
    namespace repositories {
      namespace jpa {
        interface com.example.demo.repositories.jpa.AddressJpaRepository {
            {abstract} + findAll()
            {abstract} + findAllByPersonId()
            {abstract} + findById()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace repositories {
      namespace jpa {
        interface com.example.demo.repositories.jpa.AdminJpaRepository {
            {abstract} + findAll()
            {abstract} + findById()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace repositories {
      namespace jpa {
        interface com.example.demo.repositories.jpa.CountryJpaRepository {
            {abstract} + findAll()
            {abstract} + findByCode()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace repositories {
      namespace jpa {
        interface com.example.demo.repositories.jpa.GroupJpaRepository {
            {abstract} + findAll()
            {abstract} + findById()
            {abstract} + findByName()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace repositories {
      namespace jpa {
        interface com.example.demo.repositories.jpa.PersonJpaRepository {
            {abstract} + existsByEmail()
            {abstract} + existsByUsername()
            {abstract} + findAll()
            {abstract} + findById()
            {abstract} + findByLastName()
            {abstract} + findByUsername()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace repositories {
      namespace jpa {
        interface com.example.demo.repositories.jpa.RoleJpaRepository {
            {abstract} + findByName()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
