@startuml

title __SERVICES's Class Diagram__\n

  namespace com.example.demo {
    namespace security {
      namespace services {
        class com.example.demo.security.services.UserDetailsImpl {
            - authorities : Collection<? extends GrantedAuthority>
            - email : String
            - password : String
            {static} - serialVersionUID : long
            - username : String
            + UserDetailsImpl()
            {static} + build()
            + equals()
            + getAuthorities()
            + getEmail()
            + getId()
            + getPassword()
            + getUsername()
            + isAccountNonExpired()
            + isAccountNonLocked()
            + isCredentialsNonExpired()
            + isEnabled()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace security {
      namespace services {
        class com.example.demo.security.services.UserDetailsServiceImpl {
            + loadUserByUsername()
        }
      }
    }
  }
  

  com.example.demo.security.services.UserDetailsImpl .up.|> org.springframework.security.core.userdetails.UserDetails
  com.example.demo.security.services.UserDetailsImpl o-- com.example.demo.domain.valueobjects.PersonId : id
  com.example.demo.security.services.UserDetailsServiceImpl .up.|> org.springframework.security.core.userdetails.UserDetailsService
  com.example.demo.security.services.UserDetailsServiceImpl o-- com.example.demo.repositories.PersonRepository : userRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
