@startuml

title __VALUEOBJECTS's Class Diagram__\n

  namespace com.example.demo {
    namespace domain {
      namespace valueobjects {
        enum ERole {
          ROLE_ADMIN
          ROLE_MODERATOR
          ROLE_USER
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace domain {
      namespace valueobjects {
        interface com.example.demo.domain.valueobjects.EntityId {
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace domain {
      namespace valueobjects {
        class com.example.demo.domain.valueobjects.GroupId {
            - groupId : long
            {static} - serialVersionUID : long
            + GroupId()
            + equals()
            + hashCode()
            + toString()
            # GroupId()
            # canEqual()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace domain {
      namespace valueobjects {
        class com.example.demo.domain.valueobjects.LedgerId {
            - id : long
            + LedgerId()
            + getId()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace domain {
      namespace valueobjects {
        class com.example.demo.domain.valueobjects.PersonId {
            - personId : long
            {static} - serialVersionUID : long
            + PersonId()
            + PersonId()
            + equals()
            + hashCode()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace com.example.demo {
    namespace domain {
      namespace valueobjects {
        class com.example.demo.domain.valueobjects.RoleId {
            - roleId : long
            {static} - serialVersionUID : long
            + RoleId()
            + RoleId()
            + equals()
            + hashCode()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  com.example.demo.domain.valueobjects.GroupId .up.|> com.example.demo.domain.valueobjects.EntityId
  com.example.demo.domain.valueobjects.GroupId .up.|> java.io.Serializable
  com.example.demo.domain.valueobjects.PersonId .up.|> com.example.demo.domain.valueobjects.EntityId
  com.example.demo.domain.valueobjects.PersonId .up.|> java.io.Serializable
  com.example.demo.domain.valueobjects.RoleId .up.|> com.example.demo.domain.valueobjects.EntityId
  com.example.demo.domain.valueobjects.RoleId .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
